### ISSUE TITLE
no file asyncHelper.1555519403262.js

### ISSUE THREAD

**Issue by SumNeuron** [leebyron/rollup-plugin-async#4]
might be similar to to the other issue (#1 ) on macOS...

I get `fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink '/var/folders/44/t12v1dk50d36hz2gq9b_dfvw0000gp/T/asyncHelper.1555519403262.js'
    at Object.unlinkSync (fs.js:952:3)
    at process.<anonymous> (/Users/sumner/Projects/<project>/node_modules/rollup-plugin-async/index.js:44:10)
    at process.emit (events.js:182:13)`

**Comment by SumNeuron** [comment]
```js
scripts: {
   "build": "npm run build:unpkg & npm run build:es & npm run build:umd",
    "build:umd": "rollup --config rollup.config.js --format umd --file dist/raab.umd.js",
    "build:es": "rollup --config rollup.config.js --format es --file dist/raab.esm.js",
    "build:unpkg": "rollup --config rollup.config.js --format iife --file dist/raab.min.js",
}
```

interestingly when I run `npm run build` i get this error. Running one at a time, it does not occur..

MWE:
git repo: https://gitlab.com/SumNeuron/raab

Test the async function:
codesandbox: https://codesandbox.io/s/6ynk7mqpvw


I have another project that essentially shares this structure, and I get an far different error

https://codesandbox.io/s/pyx14r6jpm

**Comment by yankeeinlondon** [comment]
I am experiencing the same problem; appears maybe this plugin has been abandoned?
